ibexa:
    system:
        site:
            content_view:
                # full pour les pages entières
                full:
                    home_page:
                        # appelle la méthode pagingQueryAction du contrôleur ibexa_query qui récupère le contenu avec une pagination
                        controller: ibexa_query::pagingQueryAction
                        # template affichant le content
                        template: full/home_page.html.twig
                        # récupère le contenu dont l'id de location est 2
                        match:
                            Id\Location: 2
                        params:
                            # permet un contrôle plus précis sur la requête et ses résultats
                            query:
                                query_type: Ride
                                limit: 2
                                # variables rides accessible côté template
                                assign_results_to: rides
                    ride:
                        # appelle la méthode viewRideWithLandmarksAction du contrôleur RideController que l'on a crée
                        controller: App\Controller\RideController::viewRideWithLandmarksAction
                        template: full/ride.html.twig
                        match:
                            # récupère le contenu dont le type est ride
                            Identifier\ContentType: ride
                # full pour les élements d'une page
                line:
                    ride:
                        template: line/rides.html.twig
                        match:
                            Identifier\ContentType: ride
                    landmark:
                        template: line/landmark.html.twig
                        match:
                            Identifier\ContentType: landmark
